# Generated by Django 4.2.3 on 2023-07-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCityAndCapitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('capital', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Store City and Capitals',
            },
        ),
    ]
