# Generated by Django 4.2.3 on 2023-07-23 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storecityandcapitals',
            options={'verbose_name': 'Store City and Capitals', 'verbose_name_plural': 'Store City and Capitals'},
        ),
    ]
